# Generated by Django 3.0.5 on 2020-04-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20200419_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='check_type',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
