# Generated by Django 3.0.5 on 2020-04-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20200419_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='check_type',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
