# Generated by Django 3.0.5 on 2020-04-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20200419_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regis_school',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
