# Generated by Django 3.0.5 on 2020-04-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('relation', models.CharField(max_length=255)),
                ('work', models.TextField(null=True)),
                ('income', models.IntegerField(null=True)),
                ('address', models.TextField()),
                ('type_house', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
    ]
