# Generated by Django 3.0.5 on 2020-04-12 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('course_id', models.CharField(max_length=8)),
                ('room', models.CharField(max_length=4, null=True)),
                ('weekday', models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('TH', 'Thursday'), ('F', 'Friday'), ('S', 'Saturday'), ('Su', 'Sunday')], max_length=2)),
                ('capacity', models.SmallIntegerField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='tel',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='type_house',
            new_name='type_of_house',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='work',
            new_name='workplace',
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=12)),
                ('room', models.SmallIntegerField()),
                ('teacher_user_id', models.CharField(max_length=6)),
                ('image', models.ImageField(null=True, upload_to='uploads/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('age', models.SmallIntegerField()),
                ('phone_number', models.CharField(max_length=12)),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('Fe', 'Female')], max_length=2)),
                ('class_room', models.CharField(max_length=6)),
                ('stu_no', models.SmallIntegerField()),
                ('track', models.CharField(max_length=25)),
                ('student_user_id', models.CharField(max_length=5)),
                ('parent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Parent')),
                ('teacher_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Teacher')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Regis_school',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('check_type', models.BooleanField()),
                ('score', models.SmallIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Course')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teach_course',
            field=models.ManyToManyField(to='school.Teacher'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField()),
                ('score_percent', models.SmallIntegerField()),
                ('session', models.SmallIntegerField()),
                ('enroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Enroll')),
            ],
        ),
    ]
