# Generated by Django 3.0.5 on 2020-04-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_student_student_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_user_id',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
